const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const output = new URL('../docs/verification/', import.meta.url);
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
const errors = [];
const context = await browser.newContext({ viewport: { width: 375, height: 812 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
await context.addInitScript(() => { Object.defineProperty(window, 'DeviceOrientationEvent', { value: undefined, configurable: true }); });
const page = await context.newPage();
page.on('pageerror', e => errors.push(e.message));
await page.clock.install();
await page.clock.pauseAt(new Date(Date.now() + 1000));
const state = () => page.evaluate(() => window.__corogalism.state);
const click = async (id) => { await page.locator(`#${id}`).click({ force: true }); await page.clock.runFor(32); };
const goal = () => page.evaluate(() => { const g = window.__corogalism.state.goal; window.__corogalism.teleport(g.x, g.y); });
const timeout = async () => { await page.evaluate(() => window.__corogalism.teleport(0.5, 0.5)); await page.clock.fastForward((await state()).limitSec * 1000 + 100); };
try {
  await page.goto('http://127.0.0.1:8765/?debug=1&seed=123');
  await page.clock.runFor(32);
  assert.equal(await page.locator('section.panel:visible').count(), 1);
  await click('btn-start');
  assert.equal((await state()).screen, 'mode');
  await page.screenshot({ path: fileURLToPath(new URL('mode-375.png', output)), fullPage: true });
  await click('btn-practice');
  let s = await state();
  assert.equal(s.hp, null); assert.equal(s.limitSec, null); assert.equal(s.seed, 123);
  assert.ok(s.walls.every(w => w.materialId === 'default'));
  const board = await page.locator('#board').boundingBox();
  await page.mouse.move(board.x + board.width * 0.5, board.y + board.height * 0.9);
  await page.mouse.down(); await page.clock.runFor(200); await page.mouse.up();
  assert.equal((await state()).started, true);
  await click('btn-pause');
  const pauseTime = (await state()).timeMs;
  await page.clock.fastForward(60000);
  assert.equal((await state()).timeMs, pauseTime);
  await click('btn-pause');
  await page.clock.runFor(100);
  assert.ok((await state()).timeMs < pauseTime + 250);
  await click('btn-game-settings');
  const settingsTime = (await state()).timeMs;
  await page.clock.fastForward(60000); await click('btn-settings-close');
  assert.equal((await state()).timeMs, settingsTime); assert.equal((await state()).paused, true);
  await click('btn-pause');
  await goal(); await page.clock.runFor(32);
  assert.equal((await state()).screen, 'clear');
  assert.ok(await page.evaluate(() => JSON.parse(localStorage.getItem('corogalism-bests'))['123']));
  await click('btn-retry'); assert.equal((await state()).seed, 123); assert.equal((await state()).timeMs, 0);
  await click('btn-game-exit'); await click('btn-challenge');
  s = await state(); const firstSeed = s.seed;
  assert.ok(s.hp.value > 0); assert.equal(s.stageIndex, 1); assert.ok(s.limitSec > 0);
  await page.clock.fastForward(30000); assert.equal((await state()).timeMs, 0);
  await page.screenshot({ path: fileURLToPath(new URL('challenge-375.png', output)), fullPage: true });
  const bounds = await page.locator('#board').boundingBox();
  const pauseBounds = await page.locator('#btn-pause').boundingBox();
  assert.ok(bounds.y >= 0 && bounds.y + bounds.height <= 812);
  assert.ok(pauseBounds.y + pauseBounds.height <= 812);
  assert.ok(Math.abs(bounds.width - bounds.height) < 2);
  await goal(); await page.clock.runFor(32);
  assert.equal((await state()).run.stages, 1); assert.equal(await page.locator('#btn-retry').isVisible(), false);
  await page.screenshot({ path: fileURLToPath(new URL('clear-375.png', output)), fullPage: true });
  await click('btn-next'); s = await state();
  assert.equal(s.stageIndex, 2); assert.notEqual(s.seed, firstSeed); assert.equal(s.hp.value, s.hp.max);
  const failedSeed = s.seed; const walls = s.walls;
  await timeout(); assert.equal((await state()).status, 'timeout'); assert.equal((await state()).screen, 'over');
  assert.equal(await page.locator('#over-heading').textContent(), '時間切れ');
  let records = await page.evaluate(() => JSON.parse(localStorage.getItem('corogalism-run-bests')));
  assert.equal(records.noContinue.stages, 1); assert.equal(records.withContinue, null);
  await page.screenshot({ path: fileURLToPath(new URL('over-375.png', output)), fullPage: true });
  await click('btn-continue'); s = await state();
  assert.equal(s.seed, failedSeed); assert.deepEqual(s.walls, walls); assert.equal(s.hp.value, s.hp.max);
  assert.equal(s.run.continuesLeft, 1); assert.equal(s.timeMs, 0);
  await goal(); await page.clock.runFor(32); await click('btn-next');
  await timeout(); await click('btn-continue'); assert.equal((await state()).run.continuesLeft, 0);
  await timeout(); assert.equal(await page.locator('#btn-continue').isDisabled(), true);
  await click('btn-run-end');
  assert.equal((await state()).screen, 'run-result');
  records = await page.evaluate(() => JSON.parse(localStorage.getItem('corogalism-run-bests')));
  assert.equal(records.noContinue.stages, 1); assert.equal(records.withContinue.stages, 2);
  await page.screenshot({ path: fileURLToPath(new URL('result-375.png', output)), fullPage: true });
  await page.reload(); await page.clock.runFor(32); await click('btn-start');
  assert.match(await page.locator('#mode-best-no').textContent(), /1面/);
  assert.match(await page.locator('#mode-best-continue').textContent(), /2面/);
  await click('btn-challenge');
  await page.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, value: true }); document.dispatchEvent(new Event('visibilitychange')); });
  await page.clock.fastForward(60000);
  await page.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, value: false }); document.dispatchEvent(new Event('visibilitychange')); });
  assert.equal((await state()).paused, true); assert.equal((await state()).timeMs, 0);
  for (const viewport of [{ width: 320, height: 568 }, { width: 390, height: 844 }, { width: 1280, height: 900 }]) {
    await page.setViewportSize(viewport); await page.clock.runFor(32);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false);
    const rect = await page.locator('#board').boundingBox();
    assert.ok(rect.x >= 0 && rect.x + rect.width <= viewport.width);
  }
  await page.goto('http://127.0.0.1:8765/');
  assert.equal(await page.evaluate(() => '__corogalism' in window), false);
  assert.deepEqual(errors, []);
  console.log('PASS: practice, pointer input, pause/settings/visibility, challenge clear/timeout/continue limit, separate records/reload, mobile layout, production hook absence; no page errors.');
} finally { await browser.close(); }
