import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base = new URL(process.env.BASE_URL || 'http://127.0.0.1:8765/');
const output = new URL('../docs/verification/audio/', import.meta.url);
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
const errors = [];
async function open({ failure, delayed = false } = {}) {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 });
  await context.addInitScript(() => Object.defineProperty(window, 'DeviceOrientationEvent', { value: undefined, configurable: true }));
  if (failure === 'api') await context.addInitScript(() => { window.AudioContext = undefined; window.webkitAudioContext = undefined; });
  if (failure === 'fetch') await context.route('**/assets/audio/*', route => route.abort());
  const pending = [];
  if (delayed) await context.route('**/assets/audio/*', route => { pending.push(route); });
  const page = await context.newPage(); page.on('pageerror', e => errors.push(e.message));
  const requests = []; page.on('request', r => { if (r.url().includes('/assets/audio/')) requests.push(r.url()); });
  await page.clock.install(); await page.clock.pauseAt(new Date(Date.now() + 1000));
  await page.goto(new URL('?debug=1&seed=123', base).href); await page.clock.runFor(32);
  const state = () => page.evaluate(() => window.__corogalism.state);
  const click = async id => { await page.locator(`#${id}`).click(); await page.clock.runFor(32); };
  const ready = () => page.clock.runFor(3100);
  const clear = async () => { await page.evaluate(() => { const g = window.__corogalism.state.goal; window.__corogalism.teleport(g.x, g.y); }); await page.clock.runFor(32); };
  return { context, page, state, click, ready, clear, requests, pending };
}
try {
  const { context, page, state, click, ready, clear, requests } = await open();
  assert.equal((await state()).audio.context, 'none'); assert.equal(requests.length, 0);
  await click('btn-mode-settings'); await click('btn-settings-sound');
  await page.waitForFunction(() => window.__corogalism.state.audio.loaded, null, { polling: 50 });
  assert.equal((await state()).audio.buffers, 14); assert.equal((await state()).audio.context, 'running');
  assert.equal((await state()).audio.music, false);
  await page.screenshot({ path: fileURLToPath(new URL('settings-390.png', output)), fullPage: true });
  await click('btn-settings-close'); assert.equal((await state()).audio.music, true);
  await click('btn-challenge'); await ready();
  assert.equal((await state()).audio.events.filter(e => e === 'countdown').length, 4);
  const audioBox = await page.locator('#btn-sound').boundingBox(), pauseBox = await page.locator('#btn-pause').boundingBox();
  assert.ok(audioBox.x + audioBox.width <= pauseBox.x); assert.ok(Math.abs(audioBox.y - pauseBox.y) < 1);
  assert.equal(await page.locator('#dev-note').isVisible(), true);
  await page.screenshot({ path: fileURLToPath(new URL('game-390.png', output)), fullPage: true });
  await page.evaluate(() => window.__corogalism.setTilt(1, 0)); await page.clock.runFor(150);
  assert.ok((await state()).audio.events.includes('rolling'));
  await page.clock.runFor(1500); assert.ok((await state()).audio.events.includes('wall'));
  await click('btn-pause'); assert.equal((await state()).audio.music, false); assert.equal((await state()).audio.rolling, false);
  assert.ok((await state()).audio.events.includes('pause'));
  await click('btn-resume'); await ready(); await clear();
  assert.equal((await state()).screen, 'clear'); assert.ok((await state()).audio.events.includes('goal')); assert.ok((await state()).audio.events.includes('clear'));
  await click('btn-next'); await ready();
  await page.evaluate(() => window.__corogalism.teleport(.5, .5)); await page.clock.fastForward((await state()).limitSec * 1000 + 50);
  assert.equal((await state()).screen, 'over'); assert.ok((await state()).audio.events.includes('fail'));
  await click('btn-continue'); assert.ok((await state()).audio.events.includes('continue'));
  await click('btn-game-settings');
  await page.locator('#set-bgm-volume').fill('0'); await page.locator('#set-se-volume').fill('25');
  assert.equal((await state()).audio.bgmVolume, 0); assert.equal((await state()).audio.seVolume, .25);
  await click('btn-settings-close'); await click('btn-resume'); assert.equal((await state()).audio.music, false);
  await click('btn-sound'); assert.equal((await state()).audio.enabled, false); assert.equal((await state()).audio.voices, 0);
  await click('btn-sound');
  await page.evaluate(() => { Object.defineProperty(document, 'hidden', { value: true, configurable: true }); document.dispatchEvent(new Event('visibilitychange')); });
  assert.equal((await state()).paused, true); assert.equal((await state()).audio.music, false); assert.equal((await state()).audio.voices, 0);
  await page.reload(); await page.clock.runFor(32);
  assert.equal((await state()).audio.enabled, true); assert.equal((await state()).audio.context, 'none');
  assert.equal((await state()).audio.seVolume, .25); assert.equal((await state()).audio.bgmVolume, 0);
  await context.close();
  for (const failure of ['api', 'fetch']) {
    const app = await open({ failure }); await app.click('btn-mode-settings'); await app.click('btn-settings-sound');
    if (failure === 'fetch') await app.page.waitForFunction(() => window.__corogalism.state.audio.loaded, null, { polling: 50 });
    assert.ok((await app.page.locator('#sound-note').textContent()).length > 0);
    await app.click('btn-settings-close'); await app.click('btn-practice'); await app.ready(); await app.clear();
    assert.equal((await app.state()).screen, 'clear'); await app.context.close();
  }
  const slow = await open({ delayed: true }); await slow.click('btn-practice'); await slow.click('btn-sound');
  for (let i = 0; slow.pending.length < 14 && i < 100; i++) await new Promise(resolve => setTimeout(resolve, 50));
  assert.equal(slow.pending.length, 14);
  await slow.click('btn-sound'); await Promise.all(slow.pending.map(route => route.continue()));
  await slow.page.waitForFunction(() => window.__corogalism.state.audio.loaded, null, { polling: 50 });
  assert.equal((await slow.state()).audio.music, false); assert.equal((await slow.state()).audio.voices, 0);
  await slow.context.close(); assert.deepEqual(errors, []);
  console.log('PASS: opt-in loading, 14 decoded sounds, countdown/rolling/impact/clear/fail/continue, pause/settings/visibility stop, independent persisted volume, approved toolbar, missing API/fetch failure and mute during loading.');
} finally { await browser.close(); }
